version: '3'

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: elections
    ports:
      - "5432:5432"